spring.datasource.url=jdbc:postgresql://filmbook-database-13758.8nj.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=C:/Users/Bombolel/AppData/Roaming/postgresql/root.crt
spring.datasource.username=ola
spring.datasource.password=GPkQv_eF3NPGLbni17XPeg
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

logging.level.org.springframework.security=TRACE


spring.security.user.name=a
spring.security.user.password=a

